# Generated by Django 4.2.5 on 2023-09-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_courses', models.TextField(help_text='Courses completed')),
                ('required_courses', models.TextField(help_text='Courses left till graduation')),
                ('degree_name', models.CharField(help_text='Student degree', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Student last name, first name', max_length=50)),
                ('student_id', models.IntegerField(help_text='ID number for student')),
            ],
        ),
    ]
